language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-susicomponent' ]; then cd .. && eval "mv $currentfolder generator-susicomponent" && cd generator-susicomponent; fi
